applications:
  - name: django-app
    namespace: default
    project: default
    source:
      repoURL: https://github.com/YOUR_GITHUB_USERNAME/DevOps_CI-CD_HW
      path: lesson-8-9/charts/django-app
      targetRevision: main
      helm:
        valueFiles:
          - values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

repositories:
  - name: example-app
    url: https://github.com/YOUR_GITHUB_USERNAME/DevOps_CI-CD_HW
    username: YOUR_GITHUB_USERNAME
    password: YOUR_GITHUB_PAT

repoConfig:
  insecure: "true"
  enableLfs: "true"
