image:
  repository: 273497135368.dkr.ecr.eu-central-1.amazonaws.com/lesson-5-ecr
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

containerPort: 8000

config:
  POSTGRES_HOST: db
  POSTGRES_PORT: "5432"
  POSTGRES_USER: django_user
  POSTGRES_DB: django_db
  POSTGRES_PASSWORD: "pass2315wd"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
